### ISSUE TITLE
Another method you may like

### ISSUE THREAD

**Issue by sarpulhu** [llvllch/Bip39-Dice#7]
Some may find it easier with less calculating:
https://gist.github.com/sarpulhu/6e7dd35c34c5ee45176001320f1a0eed

**Comment by veebch** [comment]
This looks good. 

I'm not sure about the opening sentence and what to do on 5 or 6 throws. Why not just write 'odd' and 'even'?

**Comment by sarpulhu** [comment]
First roll determines first half or bottom half of list as the 1..4 chart repeats once. All the next rolls can use only 1 to 4. So 5 and 6 are ignored. Only way to perfectly map to 2048 words.
