### ISSUE TITLE
got an invalid mnemonic but successfully run the main.py

### ISSUE THREAD

**Issue by jnydfc** [llvllch/Bip39-Dice#8]
for example:
able truly wild young pony morning boss high onion now space human paper leg able history feed utility result rent enact mouse diary afraid

24th words generated by main.py:
['afraid', 'close', 'evoke', 'general', 'liberty', 'royal', 'strategy', 'wagon']

all is invalid

**Comment by veebch** [comment]
Isn't that 24 words you're putting in rolls? I'll add something to stop that error being possible.

**Comment by jnydfc** [comment]
> Isn't that 24 words you're putting in rolls? I'll add something to stop that error being possible.

you have added it, rolls.txt is mandated to have exactly 23 lines

------------------------
"able truly wild young pony morning boss high onion now space human paper leg able history feed utility result rent enact mouse diary"

these first 23 words can generate 24th word with main.py, but all words in the output list are invalid

------------------------
this is a very awesome generator in python

Probably there is some little problem, but it's   Immensely hard for me to find it out

Could you please fix it?  thank you very much

**Comment by veebch** [comment]
You're right, something is odd. I'll get it fixed tomorrow

**Comment by veebch** [comment]
Fixed! I've reverted to an almost exact copy of the code it was originally based on. I checked the results.... all valid
